# Generated by Django 3.1.13 on 2021-08-18 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.IntegerField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Newslettter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Sign_in',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sing_up',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=8, null=True)),
                ('confirm_password', models.CharField(max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Single_review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.IntegerField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mobile_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('newprice', models.IntegerField()),
                ('oldprice', models.IntegerField()),
                ('ranking', models.IntegerField()),
                ('image', models.ImageField(upload_to='media/')),
                ('amount', models.IntegerField(null=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.color')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.mobile')),
            ],
        ),
        migrations.CreateModel(
            name='Home_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('newprice', models.IntegerField()),
                ('oldprice', models.IntegerField()),
                ('ranking', models.IntegerField()),
                ('image', models.ImageField(upload_to='media/')),
                ('amount', models.IntegerField(null=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.color')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.home')),
            ],
        ),
        migrations.CreateModel(
            name='Basket_mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('newprice', models.IntegerField()),
                ('amount', models.IntegerField(default=1, null=True)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.mobile')),
            ],
        ),
        migrations.CreateModel(
            name='Basket_home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('newprice', models.IntegerField()),
                ('amount', models.IntegerField(default=1, null=True)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.home')),
            ],
        ),
        migrations.CreateModel(
            name='Basket_accesuars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('newprice', models.IntegerField()),
                ('amount', models.IntegerField(default=1, null=True)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.accessories')),
            ],
        ),
        migrations.CreateModel(
            name='Accesuar_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('newprice', models.IntegerField()),
                ('oldprice', models.IntegerField()),
                ('ranking', models.IntegerField()),
                ('image', models.ImageField(upload_to='media/')),
                ('amount', models.IntegerField(null=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.color')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.accessories')),
            ],
        ),
    ]
