# Generated by Django 3.1.13 on 2021-08-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sing_up',
            name='confirm_password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sing_up',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
